version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
#      - SERVICES=${SERVICES- }
      - SERVICES=s3,ec2,apigateway
      - DEBUG=1
      - DATA_DIR=/data
      - PORT_WEB_UI=8081
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      #- DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_vol:/tmp/localstack"
volumes:
  localstack_vol: 
